/*Q 01*/
CREATE TABLE "TB_CURSO" (
  "ID" INTEGER NOT NULL,
  "NOME" TEXT NOT NULL,
  PRIMARY KEY("ID" AUTOINCREMENT)
);

/*Q 02*/
CREATE TABLE "TB_PROFESSOR" (
	"ID"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	"CURSO_ID"	INTEGER NOT NULL,
	FOREIGN KEY("CURSO_ID") REFERENCES "TB_CURSO"("ID")
);

/*Q 03*/
CREATE TABLE "TB_CURSO_PROFESSOR" (
	"ID"	INTEGER NOT NULL,
	"CURSO_ID"	INTEGER NOT NULL,
	"PROFESSOR_ID"	TEXT NOT NULL,
	FOREIGN KEY("CURSO_ID") REFERENCES "TB_CURSO"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);

/*Q 04*/
INSERT INTO TB_CURSO (NOME)
VALUES('INFORMÁTICA');

INSERT INTO TB_CURSO (NOME)
VALUES('TELECOMUNICAÇÕES');

INSERT INTO TB_CURSO (NOME)
VALUES('ELETROTÉCNICA');

INSERT INTO TB_CURSO (NOME)
VALUES('MECÂNICA');

INSERT INTO TB_CURSO (NOME)
VALUES('EDIFICAÇÕES');

INSERT INTO TB_CURSO (NOME)
VALUES('TURISMO');

INSERT INTO TB_CURSO (NOME)
VALUES('QUÍMICA');

/*select * from TB_CURSO;( os valores do curso)*/

/*Q 05*/
INSERT INTO TB_PROFESSOR (NOME,CURSO_ID)
VALUES('CÉSAR OLAVO', 1), 
('DAVIS MACEDO', 1),
('SERRA FURTADO', 1),
('MAURÍCIO JABORANDI', 1),
('MARCOS LEMOS', 4),
('JOSÉ ROBERTO', 1),
('GLÓRIA MARINHO', 7);

/*Q 06*/
INSERT INTO TB_CURSO_PROFESSOR\(CURSO_ID, PROFESSOR_ID)
VALUES 
     
